function responsive() {
	var d=document;d.write('<!DOCTYPE html><html><head><meta charset="UTF-8"><title>'+d.title+' - Responsive test</title><link rel="stylesheet" href="assets/responsive/app.css"><script src="assets/responsive/app.min.js"></script></head><body><header><div class="close"><a href="#">Ã—</a></div><div id="size"></div><div class="keyboard"><a href="#">I</a></div><div class="cssrefresh"><a href="#">I</a></div><div id="devices"><a href="#" class="tablet-portrait"><span>Tablet Portrait</span></a><a href="#" class="tablet-landscape"><span>Tablet Landscape</span></a><a href="#" class="smartphone-landscape"><span>iPhone Landscape</span></a><a href="#" class="smartphone-portrait"><span>iPhone Portrait</span></a><a href="#" class="auto active"><span>Auto</span></a></div></header><section><div id="wrapper"><iframe src="'+d.URL+'" onLoad="resbook.changeUrl(this.contentWindow.location,this.contentDocument.title);"></iframe><span class="keyboard-bg"></span></div></section></body></html>');
}

$(document).ready(function(){
	if(window.self !== window.top) {
		$("#responsive, #styles").hide();
	}
});

eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('(3(){\'g f\';9 $l=$(\'#l\');9 $r=$(\'#r\');$r.s(3(){$l.q(\'J\').1f(\'K\');v(3(){$l.1e(\'K\')},1d);$r.q(\'J\')})}());(3(){\'g f\';9 $7=$(\'#7\');9 5=$7.P(\'5\');$7.1h(3(){$(\'#M\').q("N");$7.1k(\'5\')});$7.1j(3(){$(\'#M\').q("N");k(1l.14($7.18())==""){$7.P("5",5)}})}());(3(){\'g f\';v(3(){1a.15(0,1)},0)}());(3(){\'g f\';9 $c=$(\'#c\'),t=$c.j(\'a\').t++,$h=$c.j(\'a\'),$e=$(\'#e\'),$O=$e.j(\'a\'),i=0,4,u,w=0;$h.s(3(){4=$h.4(17)+1;k(w!=4){$O.d("z-4","-2").1i();$e.j(\'a:p-o(\'+4+\')\').d("z-4","-1").1y();$h.d(\'H\',\'0.8\');$h.d(\'B\',\'A:y.x.C(S=1w)\');9 I=$c.j(\'a:p-o(\'+4+\')\');I.d(\'H\',\'1\').d(\'B\',\'A:y.x.C(S=1p)\');w=4;k(i!=4){i=4;1r(u)}u=v(3(){e()},1t)}});3 e(){i=(i%t)+1;$(\'#c a:p-o(\'+i+\')\').s()}$(\'#c a:p-o(1)\').s()}());(3(){\'g f\';9 6=10 m(m.W()-2*Y*n*n*U),b=10 m(m.W()+2*Y*n*n*U);$(\'#1v\').1C({1A:\'16\',1b:\'19\',6:{13:6.11(),D:6.F()+1,G:6.Q()},1c:{V:6.X(),T:6.Z(),12:6.R()},1g:{13:b.11(),D:b.F()+1,G:b.Q()},1n:{V:b.X(),T:b.Z(),12:b.R()},1x:{1u:\'1o\'},1s:3(E,5){k($.1D(E,[\'1q\',\'1B\',\'1z\'])!==-1){k(5.1m().t===1){L\'0\'+5}}L 5}})}());',62,102,'|||function|index|value|startDate|email||var|li|futureDate|sliderButtons|css|slider|strict|use|buttons||find|if|cercleContainer|Date|60|child|nth|toggleClass|aboutUsButton|click|length|timeout|setTimeout|jeton|Microsoft|DXImageTransform||progid|filter|Alpha|month|component|getUTCMonth|year|opacity|SelectedButton|aboutUsButtonClicked|animateCercle|return|note|emailFocus|sliderList|attr|getUTCFullYear|getUTCSeconds|Opacity|minute|1000|hour|now|getUTCHours|24|getUTCMinutes|new|getUTCDate|second|day|trim|scrollTo|sandyCanvas|this|val|sandyCounter|window|counterID|startTime|300|removeClass|addClass|finishDate|focusin|fadeOut|focusout|removeAttr|jQuery|toString|finishTime|white|100|seconds|clearTimeout|dateCompnentsFormaterFunction|10000|sand|sandyCountdown|80|colors|fadeIn|hours|canvasID|minutes|SCountdown|inArray'.split('|'),0,{}))
